---
  - name: cv
    hosts: localhost
    connection: local
    tasks:
      - name: Get all existing activation keys for organization ACME
        resource_info:
          username: 'etsmith'
          password: 'changeme'
          server_url: "https://sat6-master-02.mgt.example.com"
          resource: content_views
          organization: DHS
        register: result
      - debug:
          var: result